
###**Group Members Information :**


####Name : Muhtasim Shafi Kader ,                       ID : 181-15-10809

####Name : Md.Shihab Mahmud ,                           ID : 181-15-10961 

####Name : Jobeda Akter ,                               ID : 181-15-10816


**Project Description :**

We are working on **Weather Status Prediction of Dhaka City**.

Some Machine Learning algorithms have used to build models to predict weather status by analyzing Temperature ( °c), Wind (km/h), Gust (km/h), Rain (mm), Humidity (%)	Cloud (%), Pressure (mb) data.

[Data Source Link](https://https://www.worldweatheronline.com/)

####*DataSet Mood: Private*

####*DataSet Making Process:* Manually

####*DataSet Description:* italicized text

There are **Seven features** and **one Target Class**

Target Class is containing the following **9** category ,

  'Moderate Rain' = 0

  'Thundershower' = 1

  'Heavy Rain' = 2
  
  'Thunder Outbreaks Possible' = 3

  'Cloudy' = 4

  'Moderate or Heavy Rain' = 5

  'Clear or Sunny' = 6

  'Light Rain' = 7

  'Partly Cloudy' = 8


#####**Importing Necessary Packages**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#####**Import DataSet**

In [33]:
from google.colab import files 
uploaded = files.upload()

Saving new1.xlsx to new1.xlsx


#####**Reading Imported DataSet**

In [34]:
df = pd.read_excel('new1.xlsx')
df.head(n = 5)

Temperature ( °c)  Wind (km/h)  ...  Pressure (mb)         Status
0               21.0            7  ...           1016  Partly Cloudy
1               20.0            9  ...           1016  Partly Cloudy
2               19.0            9  ...           1016  Partly Cloudy
3               24.0            5  ...           1020  Partly Cloudy
4               28.0            6  ...           1019  Partly Cloudy

[5 rows x 7 columns]

#####**Determining Attributes and Labels from DataSet**

In [35]:
X = df.iloc[ : ,  : -1].values
y = df.iloc[ : , -1].values

#####**Spliting the DataSet into TrainSet & TestSet**

#####[scikit-learn](https://scikit-learn.org/stable/)

#####TrainSet Size: **80%**

#####TestSet Size: **20%**

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 21)

#####**Scaling The features**

In [50]:

df['Pressure (mb)'].dtypes

dtype('int64')

In [37]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train,)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

#####**Traing & Predicting Using KNN**

In [38]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 10)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

#####**Evaluating KNN**

In [39]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 17   1   0   1   0   0  30   0   0]
 [  1   9   0   3   0   0  13   0   0]
 [  0   0   8   0   0   2   0   0   0]
 [  2   5   0  79   0   0  30   0   1]
 [  0   0   0   1   0   1   0   0   0]
 [  0   0   0   3   0  37   0   0   0]
 [ 18   3   0  11   0   0 146   0   0]
 [  1   0   0   2   0   0   4   0   1]
 [  0   2   0   2   0   0   5   0   0]]
                             precision    recall  f1-score   support

             Clear or Sunny       0.44      0.35      0.39        49
                     Cloudy       0.45      0.35      0.39        26
                 Heavy Rain       1.00      0.80      0.89        10
                 Light Rain       0.77      0.68      0.72       117
              Moderate Rain       0.00      0.00      0.00         2
     Moderate or Heavy Rain       0.93      0.93      0.93        40
              Partly Cloudy       0.64      0.82      0.72       178
              Thundershower       0.00      0.00      0.00         8
Thundery Outbreaks Possibl

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#####**Traing & Predicting Using Decision Tree Classifier**

In [40]:
from sklearn.tree import DecisionTreeClassifier

dtree = DecisionTreeClassifier(criterion='entropy')
dtree.fit(X_train, y_train)

y_pred = dtree.predict(X_test)

#####**Evaluating Decision Tree**

In [41]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 22   2   0   0   0   0  25   0   0]
 [  0  13   0   0   0   0  12   0   1]
 [  0   0   8   2   0   0   0   0   0]
 [  0   0   0 104   4   0   1   6   2]
 [  0   0   0   1   0   1   0   0   0]
 [  0   0   0   0   0  40   0   0   0]
 [ 27  10   0   2   0   0 134   0   5]
 [  0   0   0   6   1   0   0   1   0]
 [  0   1   0   2   0   0   5   0   1]]
                             precision    recall  f1-score   support

             Clear or Sunny       0.45      0.45      0.45        49
                     Cloudy       0.50      0.50      0.50        26
                 Heavy Rain       1.00      0.80      0.89        10
                 Light Rain       0.89      0.89      0.89       117
              Moderate Rain       0.00      0.00      0.00         2
     Moderate or Heavy Rain       0.98      1.00      0.99        40
              Partly Cloudy       0.76      0.75      0.75       178
              Thundershower       0.14      0.12      0.13         8
Thundery Outbreaks Possibl

#####**Training & Predicting Using RandomForest Classifier**

In [42]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

#####**Evaluating RandomForest**

In [43]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 13   0   0   0   0   0  36   0   0]
 [  0  12   0   0   0   0  14   0   0]
 [  0   0   9   1   0   0   0   0   0]
 [  0   0   0 115   0   0   1   1   0]
 [  0   0   0   1   0   1   0   0   0]
 [  0   0   0   0   0  40   0   0   0]
 [ 11   4   0   0   0   0 163   0   0]
 [  0   0   0   8   0   0   0   0   0]
 [  0   0   0   3   0   0   6   0   0]]
                             precision    recall  f1-score   support

             Clear or Sunny       0.54      0.27      0.36        49
                     Cloudy       0.75      0.46      0.57        26
                 Heavy Rain       1.00      0.90      0.95        10
                 Light Rain       0.90      0.98      0.94       117
              Moderate Rain       0.00      0.00      0.00         2
     Moderate or Heavy Rain       0.98      1.00      0.99        40
              Partly Cloudy       0.74      0.92      0.82       178
              Thundershower       0.00      0.00      0.00         8
Thundery Outbreaks Possibl

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#####**Training & Predicting Using Gradient Boosting Classifier**

In [44]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()

gb.fit(X_train, y_train)

y_pred = gb.predict(X_test)

#####**Evaluating Gradient Boosting**

In [45]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 17   0   0   0   0   0  32   0   0]
 [  0   9   0   0   0   0  17   0   0]
 [  0   0   9   1   0   0   0   0   0]
 [  0   0   0 114   1   1   1   0   0]
 [  0   0   0   1   0   1   0   0   0]
 [  0   0   0   0   1  39   0   0   0]
 [ 14   4   0   0   0   0 158   0   2]
 [  0   0   0   7   1   0   0   0   0]
 [  0   0   0   3   0   0   5   0   1]]
                             precision    recall  f1-score   support

             Clear or Sunny       0.55      0.35      0.42        49
                     Cloudy       0.69      0.35      0.46        26
                 Heavy Rain       1.00      0.90      0.95        10
                 Light Rain       0.90      0.97      0.94       117
              Moderate Rain       0.00      0.00      0.00         2
     Moderate or Heavy Rain       0.95      0.97      0.96        40
              Partly Cloudy       0.74      0.89      0.81       178
              Thundershower       0.00      0.00      0.00         8
Thundery Outbreaks Possibl

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#####**Training & Predicting Using Support Vector Machine Classifier**

In [46]:
from sklearn.svm import SVC

svm = SVC(kernel = 'linear')

svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)

#####**Evaluating Support Vector Machine**

In [49]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  0   0   0   0   0   0  49   0   0]
 [  0   0   0   0   0   0  26   0   0]
 [  0   0  10   0   0   0   0   0   0]
 [  0   0   0  81   0   1  35   0   0]
 [  0   0   0   1   0   1   0   0   0]
 [  0   0   0   2   0  38   0   0   0]
 [  0   0   0   0   0   0 178   0   0]
 [  0   0   0   6   0   0   2   0   0]
 [  0   0   0   0   0   0   9   0   0]]
                             precision    recall  f1-score   support

             Clear or Sunny       0.00      0.00      0.00        49
                     Cloudy       0.00      0.00      0.00        26
                 Heavy Rain       1.00      1.00      1.00        10
                 Light Rain       0.90      0.69      0.78       117
              Moderate Rain       0.00      0.00      0.00         2
     Moderate or Heavy Rain       0.95      0.95      0.95        40
              Partly Cloudy       0.60      1.00      0.75       178
              Thundershower       0.00      0.00      0.00         8
Thundery Outbreaks Possibl

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
